version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sample"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17zbz4wlflg0x"
s3_prefix = "sample"
region = "ap-southeast-1"
profile = "personal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

